#!/bin/sh -e

export PREFIX=""
if [ -d 'venv' ] ; then
    export PREFIX="venv/bin/"
fi
SOURCE_FILES="starlette_login tests"

set -x

${PREFIX}isort --check --diff --project=starlette_login $SOURCE_FILES
${PREFIX}black --check --diff --line-length=79 $SOURCE_FILES
${PREFIX}flake8 $SOURCE_FILES
${PREFIX}mypy starlette_login
