#!/bin/sh -e

export PREFIX=""
if [ -d 'venv' ] ; then
    export PREFIX="venv/bin/"
fi
SOURCE_FILES="starlette_login tests"

set -x

${PREFIX}autoflake --in-place --recursive ${SOURCE_FILES}
${PREFIX}isort --project=starlette_login ${SOURCE_FILES}
${PREFIX}black --line-length=79 ${SOURCE_FILES}
